version: '2'
services:
  auditing-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/auditing/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=auditing
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
